

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: 88-5AE3-8528-3A			    |
; |				 Licensed User				    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	D0FE8033AFC47107F828DA3E70ED6B48

; File Name   :	D:\DOSBox\Bin\a.out
; Format      :	ELF (Shared object)
; Interpreter '/lib64/ld-linux-x86-64.so.2'
; Needed Library 'libpthread.so.0'
; Needed Library 'libc.so.6'
;
; Source File :	'crtstuff.c'
; Source File :	'main.c'
; Source File :	'crtstuff.c'

		.686p
		.mmx
		.model flat
.intel_syntax noprefix

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_init		segment	dword public 'CODE' use64
		assume cs:_init
		;org 770h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _init_proc
_init_proc	proc near		; CODE XREF: __libc_csu_init+2Cp
		sub	rsp, 8		; _init
		mov	rax, cs:__gmon_start___ptr
		test	rax, rax
		jz	short loc_782
		call	rax ; __gmon_start__

loc_782:				; CODE XREF: _init_proc+Ej
		add	rsp, 8
		retn
_init_proc	endp

_init		ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_plt		segment	para public 'CODE' use64
		assume cs:_plt
		;org 790h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
		dq 2 dup(?)
; [00000006 BYTES: COLLAPSED FUNCTION _pthread_create. PRESS KEYPAD "+"	TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _strncpy.	PRESS KEYPAD "+" TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _puts. PRESS KEYPAD "+" TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _calloc. PRESS KEYPAD "+"	TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _fprintf.	PRESS KEYPAD "+" TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _pthread_exit. PRESS KEYPAD "+" TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _atoi. PRESS KEYPAD "+" TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _exit. PRESS KEYPAD "+" TO EXPAND]
		dw ?
		dq ?
; [00000006 BYTES: COLLAPSED FUNCTION _fwrite. PRESS KEYPAD "+"	TO EXPAND]
		dw ?
		dq ?
_plt		ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
; Segment alignment 'qword' can not be represented in assembly
_plt_got	segment	para public 'CODE' use64
		assume cs:_plt_got
		;org 830h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
; [00000006 BYTES: COLLAPSED FUNCTION __cxa_finalize. PRESS KEYPAD "+" TO EXPAND]
		align 8
_plt_got	ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_text		segment	para public 'CODE' use64
		assume cs:_text
		;org 840h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================

; Attributes: noreturn

		public _start
_start		proc near
		xor	ebp, ebp
		mov	r9, rdx
		pop	rsi
		mov	rdx, rsp
		and	rsp, 0FFFFFFFFFFFFFFF0h
		push	rax
		push	rsp
		lea	r8, __libc_csu_fini
		lea	rcx, __libc_csu_init
		lea	rdi, main
		call	cs:__libc_start_main_ptr
		hlt
_start		endp

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

deregister_tm_clones proc near		; CODE XREF: __do_global_dtors_aux:loc_923p
		lea	rdi, cs:201070h
		lea	rax, cs:201077h
		push	rbp
		sub	rax, rdi
		mov	rbp, rsp
		cmp	rax, 0Eh
		jbe	short loc_8A0
		mov	rax, cs:_ITM_deregisterTMCloneTable_ptr
		test	rax, rax
		jz	short loc_8A0
		pop	rbp
		jmp	rax
; ---------------------------------------------------------------------------
		align 20h

loc_8A0:				; CODE XREF: deregister_tm_clones+19j
					; deregister_tm_clones+25j
		pop	rbp
		retn
deregister_tm_clones endp

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

register_tm_clones proc	near		; CODE XREF: frame_dummy:loc_94Dj
					; frame_dummy+2Bj
		lea	rdi, cs:201070h
		lea	rsi, cs:201070h
		push	rbp
		sub	rsi, rdi
		mov	rbp, rsp
		sar	rsi, 3
		mov	rax, rsi
		shr	rax, 3Fh
		add	rsi, rax
		sar	rsi, 1
		jz	short loc_8F0
		mov	rax, cs:_ITM_registerTMCloneTable_ptr
		test	rax, rax
		jz	short loc_8F0
		pop	rbp
		jmp	rax
; ---------------------------------------------------------------------------
		align 10h

loc_8F0:				; CODE XREF: register_tm_clones+26j
					; register_tm_clones+32j
		pop	rbp
		retn
register_tm_clones endp

; ---------------------------------------------------------------------------
		align 20h

; =============== S U B	R O U T	I N E =======================================


__do_global_dtors_aux proc near		; DATA XREF: .fini_array:__do_global_dtors_aux_fini_array_entryo
		cmp	cs:completed_6963, 0
		jnz	short locret_930
		cmp	cs:__cxa_finalize_ptr, 0
		push	rbp
		mov	rbp, rsp
		jz	short loc_923
		mov	rdi, cs:__dso_handle
		call	__cxa_finalize

loc_923:				; CODE XREF: __do_global_dtors_aux+15j
		call	deregister_tm_clones
		pop	rbp
		mov	cs:completed_6963, 1

locret_930:				; CODE XREF: __do_global_dtors_aux+7j
		rep retn
__do_global_dtors_aux endp

; ---------------------------------------------------------------------------
		align 20h

; =============== S U B	R O U T	I N E =======================================


frame_dummy	proc near		; DATA XREF: .init_array:__frame_dummy_init_array_entryo
		lea	rdi, __JCR_LIST__
		cmp	qword ptr [rdi], 0
		jnz	short loc_958

loc_94D:				; CODE XREF: frame_dummy+22j
		jmp	register_tm_clones
; ---------------------------------------------------------------------------
		align 8

loc_958:				; CODE XREF: frame_dummy+Bj
		mov	rax, cs:_Jv_RegisterClasses_ptr
		test	rax, rax
		jz	short loc_94D
		push	rbp
		mov	rbp, rsp
		call	rax ; _Jv_RegisterClasses
		pop	rbp
		jmp	register_tm_clones
frame_dummy	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

		public main
main		proc near		; DATA XREF: _start+1Do

var_10		= qword	ptr -10h
var_4		= dword	ptr -4

		push	rbp
		mov	rbp, rsp
		sub	rsp, 10h
		mov	[rbp+var_4], edi
		mov	[rbp+var_10], rsi
		cmp	[rbp+var_4], 2
		jg	short loc_9AE
		mov	rax, [rbp+var_10]
		mov	rdx, [rax]
		mov	rax, cs:stderr@@GLIBC_2_2_5
		lea	rsi, format	; "Usage: %s <value> <len>\n"
		mov	rdi, rax	; stream
		mov	eax, 0
		call	_fprintf
		mov	eax, 0FFFFFFFFh
		jmp	short locret_9E4
; ---------------------------------------------------------------------------

loc_9AE:				; CODE XREF: main+13j
		mov	rax, [rbp+var_10]
		add	rax, 10h
		mov	rax, [rax]
		mov	rdi, rax	; nptr
		call	_atoi
		movsxd	rdx, eax
		mov	rax, [rbp+var_10]
		add	rax, 8
		mov	rax, [rax]
		mov	rsi, rdx
		mov	rdi, rax
		call	secure_cpy
		mov	edi, 0		; retval
		call	_pthread_exit
; ---------------------------------------------------------------------------

locret_9E4:				; CODE XREF: main+3Cj
		leave
		retn
main		endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

; void *check_buf(void *)
		public check_buf
check_buf	proc near		; DATA XREF: secure_cpy+2Eo

var_8		= qword	ptr -8

		push	rbp
		mov	rbp, rsp
		sub	rsp, 10h
		mov	[rbp+var_8], rdi
		mov	rax, [rbp+var_8]
		add	rax, 19h
		movzx	eax, byte ptr [rax]
		test	al, al
		jz	short loc_A17
		lea	rdi, s		; "Slava-sama, your expertize is impressiv"...
		call	_puts
		mov	edi, 0		; status
		call	_exit
; ---------------------------------------------------------------------------

loc_A17:				; CODE XREF: check_buf+19j
		mov	eax, 0
		leave
		retn
check_buf	endp


; =============== S U B	R O U T	I N E =======================================

; Attributes: bp-based frame

		public secure_cpy
secure_cpy	proc near		; CODE XREF: main+65p

n		= dword	ptr -30h
src		= qword	ptr -28h
newthread	= dword	ptr -18h
var_C		= dword	ptr -0Ch
dest		= qword	ptr -8

		push	rbp
		mov	rbp, rsp
		sub	rsp, 30h
		mov	[rbp+src], rdi
		mov	qword ptr [rbp+n], rsi
		mov	esi, 1		; size
		mov	edi, 19h	; nmemb
		call	_calloc
		mov	[rbp+dest], rax
		mov	rdx, [rbp+dest]
		lea	rax, [rbp+newthread]
		mov	rcx, rdx	; arg
		lea	rdx, check_buf	; start_routine
		mov	esi, 0		; attr
		mov	rdi, rax	; newthread
		call	_pthread_create
		mov	rax, qword ptr [rbp+n]
		mov	[rbp+var_C], eax
		cmp	[rbp+var_C], 19h
		jle	short loc_A94
		mov	rax, cs:stderr@@GLIBC_2_2_5
		mov	rcx, rax	; s
		mov	edx, 7		; n
		mov	esi, 1		; size
		lea	rdi, aAbuse	; "Abuse!\n"
		call	_fwrite
		mov	eax, 0FFFFFFFFh
		jmp	short locret_ABC
; ---------------------------------------------------------------------------

loc_A94:				; CODE XREF: secure_cpy+4Dj
		mov	rdx, qword ptr [rbp+n] ; n
		mov	rcx, [rbp+src]
		mov	rax, [rbp+dest]
		mov	rsi, rcx	; src
		mov	rdi, rax	; dest
		call	_strncpy
		mov	rax, [rbp+dest]
		mov	rdi, rax	; s
		call	_puts
		mov	eax, 0

locret_ABC:				; CODE XREF: secure_cpy+74j
		leave
		retn
secure_cpy	endp

; ---------------------------------------------------------------------------
		align 20h

; =============== S U B	R O U T	I N E =======================================


		public __libc_csu_init
__libc_csu_init	proc near		; DATA XREF: _start+16o
		push	r15
		push	r14
		mov	r15d, edi
		push	r13
		push	r12
		lea	r12, __frame_dummy_init_array_entry
		push	rbp
		lea	rbp, __do_global_dtors_aux_fini_array_entry
		push	rbx
		mov	r14, rsi
		mov	r13, rdx
		sub	rbp, r12
		sub	rsp, 8
		sar	rbp, 3
		call	_init_proc
		test	rbp, rbp
		jz	short loc_B16
		xor	ebx, ebx
		nop	dword ptr [rax+rax+00000000h]

loc_B00:				; CODE XREF: __libc_csu_init+54j
		mov	rdx, r13
		mov	rsi, r14
		mov	edi, r15d
		call	qword ptr [r12+rbx*8]
		add	rbx, 1
		cmp	rbp, rbx
		jnz	short loc_B00

loc_B16:				; CODE XREF: __libc_csu_init+34j
		add	rsp, 8
		pop	rbx
		pop	rbp
		pop	r12
		pop	r13
		pop	r14
		pop	r15
		retn
__libc_csu_init	endp

; ---------------------------------------------------------------------------
		align 10h

; =============== S U B	R O U T	I N E =======================================


		public __libc_csu_fini
__libc_csu_fini	proc near		; DATA XREF: _start+Fo
		rep retn
__libc_csu_fini	endp

_text		ends

; ===========================================================================

; Segment type:	Pure code
; Segment permissions: Read/Execute
_fini		segment	dword public 'CODE' use64
		assume cs:_fini
		;org 0B34h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B	R O U T	I N E =======================================


		public _term_proc
_term_proc	proc near
		sub	rsp, 8		; _fini
		add	rsp, 8
		retn
_term_proc	endp

_fini		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
; Segment alignment 'qword' can not be represented in assembly
_rodata		segment	para public 'CONST' use64
		assume cs:_rodata
		;org 0B40h
		public _IO_stdin_used
_IO_stdin_used	dd 20001h
		align 8
; char format[]
format		db 'Usage: %s <value> <len>',0Ah,0 ; DATA XREF: main+23o
		align 8
; char s[]
s		db 'Slava-sama, your expertize is impressive. Congratulations',0
					; DATA XREF: check_buf+1Bo
aAbuse		db 'Abuse!',0Ah,0       ; DATA XREF: secure_cpy+63o
_rodata		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
_eh_frame_hdr	segment	dword public 'CONST' use64
		assume cs:_eh_frame_hdr
		;org 0BACh
__GNU_EH_FRAME_HDR db	 1
		db  1Bh
		db    3
		db  3Bh	; ;
		db  48h	; H
		db    0
		db    0
		db    0
		db    8
		db    0
		db    0
		db    0
		db 0E4h	; ‰
		db 0FBh	; ˚
		db 0FFh
		db 0FFh
		db  94h	; î
		db    0
		db    0
		db    0
		db  84h	; Ñ
		db 0FCh	; ¸
		db 0FFh
		db 0FFh
		db 0BCh	; º
		db    0
		db    0
		db    0
		db  94h	; î
		db 0FCh	; ¸
		db 0FFh
		db 0FFh
		db  64h	; d
		db    0
		db    0
		db    0
		db 0C4h	; ƒ
		db 0FDh	; ˝
		db 0FFh
		db 0FFh
		db 0D4h	; ‘
		db    0
		db    0
		db    0
		db  3Ah	; :
		db 0FEh	; ˛
		db 0FFh
		db 0FFh
		db 0F4h	; Ù
		db    0
		db    0
		db    0
		db  72h	; r
		db 0FEh	; ˛
		db 0FFh
		db 0FFh
		db  14h
		db    1
		db    0
		db    0
		db  14h
		db 0FFh
		db 0FFh
		db 0FFh
		db  34h	; 4
		db    1
		db    0
		db    0
		db  84h	; Ñ
		db 0FFh
		db 0FFh
		db 0FFh
		db  7Ch	; |
		db    1
		db    0
		db    0
_eh_frame_hdr	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read
; Segment alignment 'qword' can not be represented in assembly
_eh_frame	segment	para public 'CONST' use64
		assume cs:_eh_frame
		;org 0BF8h
		db  14h
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    1
		db  7Ah	; z
		db  52h	; R
		db    0
		db    1
		db  78h	; x
		db  10h
		db    1
		db  1Bh
		db  0Ch
		db    7
		db    8
		db  90h	; ê
		db    1
		db    7
		db  10h
		db  14h
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  28h	; (
		db 0FCh	; ¸
		db 0FFh
		db 0FFh
		db  2Bh	; +
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db  14h
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    1
		db  7Ah	; z
		db  52h	; R
		db    0
		db    1
		db  78h	; x
		db  10h
		db    1
		db  1Bh
		db  0Ch
		db    7
		db    8
		db  90h	; ê
		db    1
		db    0
		db    0
		db  24h	; $
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  48h	; H
		db 0FBh	; ˚
		db 0FFh
		db 0FFh
		db 0A0h	; †
		db    0
		db    0
		db    0
		db    0
		db  0Eh
		db  10h
		db  46h	; F
		db  0Eh
		db  18h
		db  4Ah	; J
		db  0Fh
		db  0Bh
		db  77h	; w
		db    8
		db  80h	; Ä
		db    0
		db  3Fh	; ?
		db  1Ah
		db  3Bh	; ;
		db  2Ah	; *
		db  33h	; 3
		db  24h	; $
		db  22h	; "
		db    0
		db    0
		db    0
		db    0
		db  14h
		db    0
		db    0
		db    0
		db  44h	; D
		db    0
		db    0
		db    0
		db 0C0h	; ¿
		db 0FBh	; ˚
		db 0FFh
		db 0FFh
		db    8
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  5Ch	; \
		db    0
		db    0
		db    0
		db 0E8h	; Ë
		db 0FCh	; ¸
		db 0FFh
		db 0FFh
		db  76h	; v
		db    0
		db    0
		db    0
		db    0
		db  41h	; A
		db  0Eh
		db  10h
		db  86h	; Ü
		db    2
		db  43h	; C
		db  0Dh
		db    6
		db    2
		db  71h	; q
		db  0Ch
		db    7
		db    8
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  7Ch	; |
		db    0
		db    0
		db    0
		db  3Eh	; >
		db 0FDh	; ˝
		db 0FFh
		db 0FFh
		db  38h	; 8
		db    0
		db    0
		db    0
		db    0
		db  41h	; A
		db  0Eh
		db  10h
		db  86h	; Ü
		db    2
		db  43h	; C
		db  0Dh
		db    6
		db  73h	; s
		db  0Ch
		db    7
		db    8
		db    0
		db    0
		db    0
		db  1Ch
		db    0
		db    0
		db    0
		db  9Ch	; ú
		db    0
		db    0
		db    0
		db  56h	; V
		db 0FDh	; ˝
		db 0FFh
		db 0FFh
		db 0A0h	; †
		db    0
		db    0
		db    0
		db    0
		db  41h	; A
		db  0Eh
		db  10h
		db  86h	; Ü
		db    2
		db  43h	; C
		db  0Dh
		db    6
		db    2
		db  9Bh	; õ
		db  0Ch
		db    7
		db    8
		db    0
		db    0
		db  44h	; D
		db    0
		db    0
		db    0
		db 0BCh	; º
		db    0
		db    0
		db    0
		db 0D8h	; ÿ
		db 0FDh	; ˝
		db 0FFh
		db 0FFh
		db  65h	; e
		db    0
		db    0
		db    0
		db    0
		db  42h	; B
		db  0Eh
		db  10h
		db  8Fh	; è
		db    2
		db  42h	; B
		db  0Eh
		db  18h
		db  8Eh	; é
		db    3
		db  45h	; E
		db  0Eh
		db  20h
		db  8Dh	; ç
		db    4
		db  42h	; B
		db  0Eh
		db  28h	; (
		db  8Ch	; å
		db    5
		db  48h	; H
		db  0Eh
		db  30h	; 0
		db  86h	; Ü
		db    6
		db  48h	; H
		db  0Eh
		db  38h	; 8
		db  83h	; É
		db    7
		db  4Dh	; M
		db  0Eh
		db  40h	; @
		db  72h	; r
		db  0Eh
		db  38h	; 8
		db  41h	; A
		db  0Eh
		db  30h	; 0
		db  41h	; A
		db  0Eh
		db  28h	; (
		db  42h	; B
		db  0Eh
		db  20h
		db  42h	; B
		db  0Eh
		db  18h
		db  42h	; B
		db  0Eh
		db  10h
		db  42h	; B
		db  0Eh
		db    8
		db    0
		db  14h
		db    0
		db    0
		db    0
		db    4
		db    1
		db    0
		db    0
		db    0
		db 0FEh	; ˛
		db 0FFh
		db 0FFh
		db    2
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
__FRAME_END__	db    0
		db    0
		db    0
		db    0
_eh_frame	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_init_array	segment	para public 'DATA' use64
		assume cs:_init_array
		;org 200DC8h
__frame_dummy_init_array_entry dq offset frame_dummy ; DATA XREF: __libc_csu_init+Bo
_init_array	ends			; Alternative name is '__init_array_start'

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_fini_array	segment	para public 'DATA' use64
		assume cs:_fini_array
		;org 200DD0h
__do_global_dtors_aux_fini_array_entry dq offset __do_global_dtors_aux
					; DATA XREF: __libc_csu_init+13o
_fini_array	ends			; Alternative name is '__init_array_end'

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_jcr		segment	para public 'DATA' use64
		assume cs:_jcr
		;org 200DD8h
__JCR_LIST__	db    0			; DATA XREF: frame_dummyo
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
_jcr		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_got		segment	para public 'DATA' use64
		assume cs:_got
		;org 200FD0h
_ITM_deregisterTMCloneTable_ptr	dq offset _ITM_deregisterTMCloneTable
					; DATA XREF: deregister_tm_clones+1Br
__libc_start_main_ptr dq offset	__libc_start_main ; DATA XREF: _start+24r
__gmon_start___ptr dq offset __gmon_start__ ; DATA XREF: _init_proc+4r
_Jv_RegisterClasses_ptr	dq offset _Jv_RegisterClasses ;	DATA XREF: frame_dummy:loc_958r
_ITM_registerTMCloneTable_ptr dq offset	_ITM_registerTMCloneTable
					; DATA XREF: register_tm_clones+28r
__cxa_finalize_ptr dq offset __imp___cxa_finalize ; DATA XREF: __cxa_finalizer
					; __do_global_dtors_aux+9r
_got		ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_got_plt	segment	para public 'DATA' use64
		assume cs:_got_plt
		;org 201000h
_GLOBAL_OFFSET_TABLE_ db    ? ;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    ?	;
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
off_201018	dq offset pthread_create ; DATA	XREF: _pthread_creater
off_201020	dq offset strncpy	; DATA XREF: _strncpyr
off_201028	dq offset puts		; DATA XREF: _putsr
off_201030	dq offset calloc	; DATA XREF: _callocr
off_201038	dq offset fprintf	; DATA XREF: _fprintfr
off_201040	dq offset pthread_exit	; DATA XREF: _pthread_exitr
off_201048	dq offset atoi		; DATA XREF: _atoir
off_201050	dq offset exit		; DATA XREF: _exitr
off_201058	dq offset fwrite	; DATA XREF: _fwriter
_got_plt	ends

; ===========================================================================

; Segment type:	Pure data
; Segment permissions: Read/Write
; Segment alignment 'qword' can not be represented in assembly
_data		segment	para public 'DATA' use64
		assume cs:_data
		;org 201060h
		public data_start ; weak
data_start	db    0			; Alternative name is '__data_start'
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		public __dso_handle
__dso_handle	dq offset __dso_handle	; DATA XREF: __do_global_dtors_aux+17r
					; .data:__dso_handleo
_data		ends

; ===========================================================================

; Segment type:	Uninitialized
; Segment permissions: Read/Write
; Segment alignment '32byte' can not be represented in assembly
_bss		segment	para public 'BSS' use64
		assume cs:_bss
		;org 201080h
		assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing
		public stderr@@GLIBC_2_2_5
; FILE *stderr
stderr@@GLIBC_2_2_5 dq ?		; DATA XREF: main+1Cr secure_cpy+4Fr
					; Alternative name is 'stderr'
					; Copy of shared data
completed_6963	db ?			; DATA XREF: __do_global_dtors_auxr
					; __do_global_dtors_aux+29w
		align 10h
_bss		ends

; ===========================================================================

; Segment type:	Externs
; extern
		extrn pthread_create@@GLIBC_2_2_5:near
		extrn strncpy@@GLIBC_2_2_5:near
		extrn puts@@GLIBC_2_2_5:near
		extrn __libc_start_main@@GLIBC_2_2_5:near
		extrn calloc@@GLIBC_2_2_5:near
		extrn fprintf@@GLIBC_2_2_5:near
		extrn pthread_exit@@GLIBC_2_2_5:near
		extrn atoi@@GLIBC_2_2_5:near
		extrn exit@@GLIBC_2_2_5:near
		extrn fwrite@@GLIBC_2_2_5:near
		extrn __cxa_finalize@@GLIBC_2_2_5:near ; weak
; int pthread_create(pthread_t *newthread, const pthread_attr_t	*attr, void *(*start_routine)(void *), void *arg)
		extrn pthread_create:near ; DATA XREF: .got.plt:off_201018o
; char *strncpy(char *dest, const char *src, size_t n)
		extrn strncpy:near	; DATA XREF: .got.plt:off_201020o
; int puts(const char *s)
		extrn puts:near		; DATA XREF: .got.plt:off_201028o
		extrn __libc_start_main:near ; CODE XREF: _start+24p
					; DATA XREF: .got:__libc_start_main_ptro
; void *calloc(size_t nmemb, size_t size)
		extrn calloc:near	; DATA XREF: .got.plt:off_201030o
; int fprintf(FILE *stream, const char *format,	...)
		extrn fprintf:near	; DATA XREF: .got.plt:off_201038o
; void pthread_exit(void *retval)
		extrn pthread_exit:near	; DATA XREF: .got.plt:off_201040o
; int atoi(const char *nptr)
		extrn atoi:near		; DATA XREF: .got.plt:off_201048o
; void exit(int	status)
		extrn exit:near		; DATA XREF: .got.plt:off_201050o
; size_t fwrite(const void *ptr, size_t	size, size_t n,	FILE *s)
		extrn fwrite:near	; DATA XREF: .got.plt:off_201058o
		extrn __imp___cxa_finalize:near	; weak ; DATA XREF: .got:__cxa_finalize_ptro
		extrn _ITM_deregisterTMCloneTable ; weak
					; DATA XREF: .got:_ITM_deregisterTMCloneTable_ptro
		extrn __gmon_start__:near ; weak ; CODE	XREF: _init_proc+10p
					; DATA XREF: .got:__gmon_start___ptro
		extrn _Jv_RegisterClasses:near ; weak ;	CODE XREF: frame_dummy+28p
					; DATA XREF: .got:_Jv_RegisterClasses_ptro
		extrn _ITM_registerTMCloneTable	; weak
					; DATA XREF: .got:_ITM_registerTMCloneTable_ptro


		end _start
